development:
  adapter: postgresql
  encoding: unicode
  database: casmoclap_dev
  username: postgres
  password: postgres
  host: localhost
  pool: 5

#production:
#  adapter: mysql2
#  database: casmoklap_production
#  encoding: utf8
#  username: root
#  password: root
#  host: localhost
production:
  adapter: postgresql
  encoding: unicode
  #database: casmoclap_production
  database: casmoclap_prod
  username: postgres
  password: postgres
  host: localhost
  pool: 5
